# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Frame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Frame

   pod 'MaterialComponents/Buttons'
   pod 'MaterialComponents/Buttons+ButtonThemer'
   pod 'MaterialComponents/Buttons+ColorThemer'
   pod 'MaterialComponents/Buttons+TypographyThemer'
   pod 'MaterialComponents/Buttons+ShapeThemer'

end
